ready for release. paul
svn@36272

diff --git a/wiki/upload-to-wiki b/wiki/upload-to-wiki
--- a/wiki/upload-to-wiki
+++ b/wiki/upload-to-wiki
@@ -6,7 +6,7 @@
 ## within a space of the directory it contains.
 
 UPLOAD_HOST=`echo $UPLOAD_TO | sed 's|.*://\([^/]*\).*|\1|'`
-UPLOAD_AUTH=`grep $UPLOAD_HOST ${HOME}/.upload-auth | sed 's|[^:]*:||'`
+UPLOAD_AUTH=`grep $UPLOAD_HOST ${HOME}/.upload-auth | sed 's|[^ ]*  *||'`
 export UPLOAD_AUTH
 UPLOAD_TARGET=`echo $UPLOAD_TO | sed "s|://|://${UPLOAD_AUTH}@|"`
 
@@ -24,8 +24,22 @@ then
   language=en
 fi
 
+## echo auth $UPLOAD_AUTH
+if [ "x$UPLOAD_AUTH" = "x" ];
+then
+  echo ""
+  echo "ERROR: Missing auth."
+  echo ""
+  exit 1
+fi
+
+## echo UPLOAD_TARGET is $UPLOAD_TARGET
 echo Uploading to $spacename/$pagename, language $language to $UPLOAD_HOST...
 cat "$file" |
   curl -k -F comment="cli-upload." -F content="<-" "$UPLOAD_TARGET/xwiki/bin/save/$spacename/$pagename?language=$language"
-
+  statusNumber="$?"
+  if [ $statusNumber != 0 ];
+  then
+  	  echo "Failed: error code ${statusNumber}."
+  fi
 done
